### ISSUE TITLE
[Question] Wait until all running jobs finish before shutdown

### ISSUE THREAD

**Issue by Dm3Ch** [aptible/supercronic#23]
Hello! Is there any way to make supercronic wait until all running jobs finish (not killing them) and only after that shutdown.

**Comment by krallin** [comment]
This is actually exactly what Supercronic does. Did you experience something different?

**Comment by Dm3Ch** [comment]
Yeah. We've got a supercronic that runs a set of cronjobs in Kubernetes. And we found that when we killing pod with supercronic, our jobs not finished.
We doesn't use any preStop command for supercronic.

Suddenly it is very important for us, because we have a lot of daily crons, that sheduled on different time. And all of them working more than hour. And when we deploying new version of our application, we have a problem with crons that were running at the moment of deploy.

@krallin Had suppercronic got any time or any another limits for shutdown for jobs?

**Comment by krallin** [comment]
Supercronic does not have any time limits for shutting down your containers, but Kubernetes does, which is probably what is killing your containers here. 

You can customize this via the `terminationGracePeriodSeconds `: https://kubernetes.io/docs/api-reference/v1.8/#podspec-v1-core

>  Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period will be used instead. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. Defaults to 30 seconds.

**Comment by krallin** [comment]
The relevant code in Supercronic is here. As you can see, no timeout: https://github.com/aptible/supercronic/blob/8e0d9341a2f211a0ed5296bf59514861f7287a70/main.go#L69-L80

**Comment by Dm3Ch** [comment]
Thank you, you were right. 

Also there's another podspec key `terminationGracePeriodSeconds:` that works on kubernetes < 1.8.
Example:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: crontab
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: cron
        command: ["/usr/local/bin/supercronic", "/crontabs/cron"]
```
